messages:
  prefix: "&bTowny &7>> "
  console-only: "&7This command can only be used by console"
  player-only: "&7This command can only be used by players"
  no-permission: "&7You do have permission to use this command"
  unknown-command: "&7Unknown arguments, type /town help"
  name-already-taken: "&7Sorry but this tag is already taken: &f%name%"
  leave-current-town: "&7Please leave your current town before using this command"
  town-created: "&7Successfully created town: &f%name%"
  no-town: "&7You must be in a town to use this command"
  name-set: "&7Towns name has been set to: %name%"
  successfully-desc: "&7Description set."
  invite-already: "&7Someone has already invited %player% to your town!"
  invite-target: "&7You have been invited to &f%name% type &8/town join %name%"
  invite-sender: "&7You have sent an invite to %player%"
  no-invite: "&7You have not been invited to %town%"
  invalid-player: "&cInvalid player: %player%"
  invalid-town: "&cInvalid town: %town%"
  successfully-joined: "&7You have successfully joined: %town%"
  new-resident: "&7A new resident has joined: %name%!"
  bank-deposit: "&7You have deposited %amount%"
  bank-withdraw: "&7You have withdrawn %amount%"